/* Generated By:JJTree: Do not edit this line. ASTConditional.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConditional extends SimpleNode {
  public ASTConditional(int id) {
    super(id);
  }

  public ASTConditional(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7f0e6fca9111ea59feddd52ee86c1ed6 (do not edit this line) */
