/* Generated By:JJTree: Do not edit this line. ASTComplexStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTComplexStatement extends SimpleNode {
  public ASTComplexStatement(int id) {
    super(id);
  }

  public ASTComplexStatement(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1c0400cbebf1c06013bf2a024500e748 (do not edit this line) */
