/* Generated By:JJTree: Do not edit this line. ASTDotExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDotExpression extends SimpleNode {
  public ASTDotExpression(int id) {
    super(id);
  }

  public ASTDotExpression(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=383adcd5aaa9e8a7ed6e426a29be74a4 (do not edit this line) */
