/* Generated By:JJTree: Do not edit this line. ASTDIV.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDIV extends SimpleNode {
  public ASTDIV(int id) {
    super(id);
  }

  public ASTDIV(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=000f6df331d8ecaadb0ced9a29596e8d (do not edit this line) */
