/* Generated By:JJTree: Do not edit this line. ASTImportClass.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportClass extends SimpleNode {
  public ASTImportClass(int id) {
    super(id);
  }

  public ASTImportClass(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=57623a70b7e413df4f309e4706d4bdaf (do not edit this line) */
