/* Generated By:JJTree: Do not edit this line. ASTImport.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImport extends SimpleNode {
  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=10a1e03152dfba1fd5b07d5172e531e9 (do not edit this line) */
