/* Generated By:JJTree: Do not edit this line. ASTImportMethod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportMethod extends SimpleNode {
  public ASTImportMethod(int id) {
    super(id);
  }

  public ASTImportMethod(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4f2f4b75ccc667c5f0a34ea8270259cf (do not edit this line) */
