/* Generated By:JJTree: Do not edit this line. ASTMUL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMUL extends SimpleNode {
  public ASTMUL(int id) {
    super(id);
  }

  public ASTMUL(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=610605d96550d8a81f2597a471ca5c63 (do not edit this line) */
