/* Generated By:JJTree: Do not edit this line. ASTNewIntObject.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNewIntObject extends SimpleNode {
  public ASTNewIntObject(int id) {
    super(id);
  }

  public ASTNewIntObject(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ae213d1e228b5526b87d9c3415a79ef (do not edit this line) */
