/* Generated By:JJTree: Do not edit this line. ASTNegation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNegation extends SimpleNode {
  public ASTNegation(int id) {
    super(id);
  }

  public ASTNegation(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90d4678f00e90ebb189ea64d156a2204 (do not edit this line) */
