/* Generated By:JJTree: Do not edit this line. ASTParseExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParseExpression extends SimpleNode {
  public ASTParseExpression(int id) {
    super(id);
  }

  public ASTParseExpression(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=20941590e388665a9d1d72eb3daeac3d (do not edit this line) */
