/* Generated By:JJTree: Do not edit this line. ASTParamethers.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTParamethers extends SimpleNode {
  public ASTParamethers(int id) {
    super(id);
  }

  public ASTParamethers(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8df13575c894060d0c93c8888031d7c3 (do not edit this line) */
