/* Generated By:JJTree: Do not edit this line. ASTSUM.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSUM extends SimpleNode {
  public ASTSUM(int id) {
    super(id);
  }

  public ASTSUM(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bec6203760f21590a5096c4f87879b1f (do not edit this line) */
