/* Generated By:JJTree: Do not edit this line. ASTSimpleStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSimpleStatement extends SimpleNode {

  public String name;
  public String valueAssigned;

  public ASTSimpleStatement(int id) {
    super(id);
  }

  public ASTSimpleStatement(Jmm p, int id) {
    super(p, id);
  }


}
/* JavaCC - OriginalChecksum=e687bfb2670c645a6ee6ed1cb077f52f (do not edit this line) */
