/* Generated By:JJTree: Do not edit this line. ASTSUB.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTSUB extends SimpleNode {
  public ASTSUB(int id) {
    super(id);
  }

  public ASTSUB(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e29a9d4236f13b74968f845875453dfb (do not edit this line) */
