/* Generated By:JJTree: Do not edit this line. ASTStatmentBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStatmentBlock extends SimpleNode {
  public ASTStatmentBlock(int id) {
    super(id);
  }

  public ASTStatmentBlock(Jmm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a91f601f068798b0fcf273ea727060f8 (do not edit this line) */
