/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
public interface JmmTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTIMPORT = 2;
  public int JJTIDENTIFIER = 3;
  public int JJTIMPORTMETHOD = 4;
  public int JJTIMPORTMETHODARGS = 5;
  public int JJTVARDECLARATION = 6;
  public int JJTTYPE = 7;
  public int JJTVOID = 8;
  public int JJTMAINDECLARATION = 9;
  public int JJTMETHODDECLARATION = 10;
  public int JJTPARAMETHERS = 11;
  public int JJTARG = 12;
  public int JJTSTATMENTBLOCK = 13;
  public int JJTSTATEMENT = 14;
  public int JJTIF = 15;
  public int JJTWHILE = 16;
  public int JJTEQUALITY = 17;
  public int JJTAND = 18;
  public int JJTLESSTHAN = 19;
  public int JJTSUM = 20;
  public int JJTSUB = 21;
  public int JJTMUL = 22;
  public int JJTDIV = 23;
  public int JJTLITERAL = 24;
  public int JJTBOOLEAN = 25;
  public int JJTDOTEXPRESSION = 26;
  public int JJTARGUMENTS = 27;
  public int JJTNEGATION = 28;
  public int JJTNEWINTOBJECT = 29;
  public int JJTNEWOBJECT = 30;


  public String[] jjtNodeName = {
    "ParseExpression",
    "ClassDeclaration",
    "Import",
    "Identifier",
    "ImportMethod",
    "ImportMethodArgs",
    "VarDeclaration",
    "Type",
    "void",
    "MainDeclaration",
    "MethodDeclaration",
    "Paramethers",
    "Arg",
    "StatmentBlock",
    "Statement",
    "If",
    "While",
    "Equality",
    "AND",
    "LESSTHAN",
    "SUM",
    "SUB",
    "MUL",
    "DIV",
    "Literal",
    "Boolean",
    "DotExpression",
    "Arguments",
    "Negation",
    "NewIntObject",
    "NewObject",
  };
}
/* JavaCC - OriginalChecksum=0b9e2a9e902bd03e9bde925378fb65da (do not edit this line) */
