/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 6.0_1 */
public interface JmmTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTVARDECLARATION = 2;
  public int JJTTYPE = 3;
  public int JJTVOID = 4;
  public int JJTMAINDECLARATION = 5;
  public int JJTMETHODDECLARATION = 6;
  public int JJTCOMPLEXSTATEMENT = 7;
  public int JJTSIMPLESTATEMENT = 8;
  public int JJTIF = 9;
  public int JJTWHILE = 10;
  public int JJTEQUALITY = 11;
  public int JJTEXPRESSION = 12;
  public int JJTAND = 13;
  public int JJTLESSTHAN = 14;
  public int JJTSUM = 15;
  public int JJTMUL = 16;
  public int JJTLITERAL = 17;
  public int JJTDOTEXPRESSION = 18;
  public int JJTNEGATION = 19;
  public int JJTNEWINTOBJECT = 20;
  public int JJTNEWOBJECT = 21;


  public String[] jjtNodeName = {
    "ParseExpression",
    "ClassDeclaration",
    "VarDeclaration",
    "Type",
    "void",
    "MainDeclaration",
    "MethodDeclaration",
    "ComplexStatement",
    "SimpleStatement",
    "If",
    "While",
    "Equality",
    "Expression",
    "AND",
    "LESSTHAN",
    "SUM",
    "MUL",
    "Literal",
    "DotExpression",
    "Negation",
    "NewIntObject",
    "NewObject",
  };
}
/* JavaCC - OriginalChecksum=9590d29f5be42c2ee8161bf1c27b4767 (do not edit this line) */
