/* Generated By:JavaCC: Do not edit this line. JmmTreeConstants.java Version 5.0 */
public interface JmmTreeConstants
{
  public int JJTPARSEEXPRESSION = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTIMPORT = 2;
  public int JJTIMPORTCLASS = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTTYPE = 5;
  public int JJTVOID = 6;
  public int JJTMAINDECLARATION = 7;
  public int JJTMETHODDECLARATION = 8;
  public int JJTPARAMETHERS = 9;
  public int JJTARG = 10;
  public int JJTSTATMENTBLOCK = 11;
  public int JJTSTATEMENT = 12;
  public int JJTIF = 13;
  public int JJTWHILE = 14;
  public int JJTEQUALITY = 15;
  public int JJTAND = 16;
  public int JJTLESSTHAN = 17;
  public int JJTSUM = 18;
  public int JJTSUB = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTLITERAL = 22;
  public int JJTBOOLEAN = 23;
  public int JJTDOTEXPRESSION = 24;
  public int JJTARGUMENTS = 25;
  public int JJTNEGATION = 26;
  public int JJTIDENTIFIER = 27;
  public int JJTNEWINTOBJECT = 28;
  public int JJTNEWOBJECT = 29;


  public String[] jjtNodeName = {
    "ParseExpression",
    "ClassDeclaration",
    "Import",
    "ImportClass",
    "VarDeclaration",
    "Type",
    "void",
    "MainDeclaration",
    "MethodDeclaration",
    "Paramethers",
    "Arg",
    "StatmentBlock",
    "Statement",
    "If",
    "While",
    "Equality",
    "AND",
    "LESSTHAN",
    "SUM",
    "SUB",
    "MUL",
    "DIV",
    "Literal",
    "Boolean",
    "DotExpression",
    "Arguments",
    "Negation",
    "Identifier",
    "NewIntObject",
    "NewObject",
  };
}
/* JavaCC - OriginalChecksum=f39b5a5a5f5191d6c640ff840f59ad4e (do not edit this line) */
